name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.8
  intl: ^0.19.0
  http: ^1.3.0
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.0
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  persistent_bottom_nav_bar_v2: ^5.3.1
  package_info_plus: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/register.png
    - assets/forgot_password.png
    - assets/camera_scan.png
    - assets/healthy_tip_1.png
    - assets/healthy_tip_2.png
    - assets/dish_icon.png
    - assets/empty_glass.png
    - assets/glass.png
